export const AchievementsDataArray = [
    {
        id: 1,
        name: 'great_turtle_1',
        title: 'Meet the Great Sea Turtle',
        completionXp: 10000,
        achievementType: 'special',
        completionParams: 'Find and talk to the great turtle',
        requirement: 10,
        isCompleted: false,
    },
    {
        id: 2,
        name: 'great_turtle_2',
        title: 'Built the Great turtle Temple',
        completionXp: 10000,
        achievementType: 'special',
        completionParams: 'Complete the contract of the great turtle Temple',
        requirement: 100,
        isCompleted: false,
    },
    {
        id: 3,
        name: 'building_collection_1',
        title: 'Collected from buildings 10 times',
        completionXp: 10000,
        achievementType: 'collection',
        completionParams: 'Collect from 10 buildings',
        requirement: 10,
        isCompleted: false,
    },
    {
        id: 4,
        name: 'building_collection_2',
        title: 'Collected from buildings 20 times',
        completionXp: 20000,
        achievementType: 'collection',
        completionParams: 'Collect from 20 buildings',
        requirement: 20,
        isCompleted: false,
    },
    {
        id: 5,
        name: 'building_collection_3',
        title: 'Collected from buildings 100 times',
        completionXp: 100000,
        achievementType: 'collection',
        completionParams: 'Collect from 100 buildings',
        requirement: 100,
        isCompleted: false,
    },
    {
        id: 6,
        name: 'battle_wins_1',
        title: 'Win your first battle',
        completionXp: 100000,
        achievementType: 'battle_wins',
        completionParams: 'Win 1 battle',
        requirement: 1,
        isCompleted: false,
    },
    {
        id: 7,
        name: 'battle_wins_2',
        title: 'Win your first battle',
        completionXp: 100000,
        achievementType: 'battle_wins',
        completionParams: 'Win 10 battle',
        requirement: 10,
        isCompleted: false,
    },
]