// Images
import Assassin from '../../assets/images/game/troops/assassin.png';
import Axeman from '../../assets/images/game/troops/axeman.png';
import Knight from '../../assets/images/game/troops/knight.png';
import Warrior from '../../assets/images/game/troops/warrior.png';

export const TroopsAvailableArray = [
  {
    id: 1,
    name: 'axe_man',
    title: 'Axe Man',
    cost: 50,
    type: 'Melee',
    timeToTrain: 10000,
    trainingPeriod: '10 Seconds',
    strength: 10,
    defense: 10,
    health: 100,
    imageUrl: Axeman,
    imageEndpoint: '/game/troops/axeman.png',
    description: 'Im an axe warrior',
  },
  {
    id: 2,
    name: 'warrior',
    title: 'Warrior',
    cost: 50,
    type: 'Melee',
    timeToTrain: 10000,
    trainingPeriod: '10 Seconds',
    strength: 10,
    defense: 10,
    health: 100,
    imageUrl: Warrior,
    imageEndpoint: '/game/troops/warrior.png',
    description: 'Im an warrior',
  },
  {
    id: 3,
    name: 'assassin',
    title: 'Assassin',
    cost: 50,
    type: 'Melee',
    timeToTrain: 10000,
    trainingPeriod: '10 Seconds',
    strength: 10,
    defense: 10,
    health: 100,
    imageUrl: Assassin,
    imageEndpoint: '/game/troops/assassin.png',
    description: 'Im an assassin',
  },
  {
    id: 4,
    name: 'knight',
    title: 'Knight',
    cost: 50,
    type: 'Melee',
    timeToTrain: 10000,
    trainingPeriod: '10 Seconds',
    strength: 10,
    defense: 10,
    health: 100,
    imageUrl: Knight,
    imageEndpoint: '/game/troops/knight.png',
    description: 'Im an knight',
  },
];
